### Create new user

POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "User1",
  "email": "User1@email.com"

}


### List all users
GET http://localhost:8080/users

### Create another user

POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "User2",
  "email": "User2@email.com"

}


### List all users again
GET http://localhost:8080/users


### User1 creates poll
POST http://localhost:8080/polls
Content-Type: application/json

{
  "question": "Why is Dat250 your favorite subject this semester?",
  "publishedAt": "2024-09-07T14:37:00Z",
  "validUntil": "2024-09-09T14:37:00Z"
}

### List Polls
GET http://localhost:8080/polls

### User2 votes on the poll
POST http://localhost:8080/votes
Content-Type: application/json

{
  "publishedAt": "2024-09-07T14:47:00Z"
}


### User2 changes votes on the poll
POST http://localhost:8080/votes
Content-Type: application/json

{
  "publishedAt": "2024-09-07T14:48:00Z"
}

### List votes
GET http://localhost:8080/votes

### Create vote option
POST http://localhost:8080/voteOptions
Content-Type: application/json

{
  "caption": "Its fun",
  "presentationOrder": 1
}

### Delete the poll
DELETE http://localhost:8080/polls/1

### List votes again
GET http://localhost:8080/votes